from services.business_proposal_service import generate_business_proposal
from services.partnership_agreement_service import generate_partnership_agreement
from services.nda_service import generate_nda
from services.contract_service import generate_contract
from services.terms_of_service_service import generate_terms_of_service
from services.privacy_policy_service import generate_privacy_policy
from services.document_utils import save_document_to_gcs
